### PR TITLE
Migrate more images to the new build system

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Depends on:

* [x] haskell https://github.com/anchore/syft/pull/3078
* [x] New Syft version for haskell
* [x] liquibase
* [x] rakudo-star (PR in Scout)
* [x] silverpeas (PR in Scout)
* [x] New Scout version that supports all of these
* [x] Update the Scanner in the build https://github.com/docker-library/official-images/pull/17699/files

### CODE REVIEW

**Review by whalelines — COMMENTED** [review]
Draft…

**Comment by LaurentGoderre** [comment]
The intent of the reorder is to make the dependencies a bit more clear

**Comment by yosifkit** [comment]
Because it was a little hard for me to follow what was moved around in `repos_anti_subset` vs what was added to the new build system, so I did some quick `jq` to compare the list before and after:
```console
$ jq -n -L . 'include "doi"; include "doi-new"; repos_anti_subset - new_repos_anti_subset'
[
  "ubuntu",
  "buildpack-deps",
  "eclipse-temurin",
  "haskell",
  "liquibase",
  "rakudo-star",
  "silverpeas"
]
```

So, these will be the additions to the new build system. This seems fine to me once you are ready. 👍

**Comment by gdams** [comment]
I've had a go at adding rakudo-star here https://github.com/anchore/syft/pull/3224

**Comment by LaurentGoderre** [comment]
@gdams there should be a new version of Scout Indexer available soon so we can close the loop

**Comment by gdams** [comment]
> @gdams there should be a new version of Scout Indexer available soon so we can close the loop

That would be great! Thanks so much

**Review by tianon — APPROVED** [review]

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
