### PR TITLE
Add `linguist-language` git attribute for GitHub's sake

### PR DESCRIPTION
**Pull request by tianon**
Otherwise, our `Jenkinsfile`s are rendered badly.

### CODE REVIEW

**Comment by tianon** [comment]
Compare
https://github.com/docker-library/meta-scripts/blob/676ab32f3fe9075dc35c4cc78962c3aa1ba065fd/Jenkinsfile.build
to
https://github.com/infosiftr/doi-meta-scripts/blob/cd19b51e2b1f33c67e310a568f417eb80e5a5747/Jenkinsfile.build

**Comment by tianon** [comment]
(it's even worse for `Jenkinsfile.trigger` that _looks_ like it's rendering sanely ... until it doesn't, because it's rendering as "Apex")

**Review by whalelines — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
CI failure is noted/described/tracked in https://github.com/docker-library/meta-scripts/issues/25 now :+1:

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
