### PR TITLE
Update sources.sh to use bashbrew 0.1.10's `ArchGitChecksum`

### PR DESCRIPTION
**Pull request by tianon**
This makes a *very* dramatic difference in the speed of `sources.sh`.

Before:

```console
$ time .scripts/sources.sh $(cat subset.txt) > sources.json
...
real	6m13.444s
user	2m51.334s
sys	3m29.256s
```

After:

```console
$ time .scripts/sources.sh $(cat subset.txt) > sources.json
...
real	0m31.238s
user	0m32.769s
sys	0m1.375s
```

### CODE REVIEW

**Comment by tianon** [comment]
Gahhhhh, I forgot I also needed the `sha256sum` function :sob:

(That's not actually what I would've chosen to name it, but that's what [Sprig](https://github.com/docker-library/bashbrew/issues/22) names it, so in the spirit of avoiding further deviance from them I chose to follow suit.)

**Comment by tianon** [comment]
https://github.com/docker-library/bashbrew/pull/90

**Comment by tianon** [comment]
Alright, this should be _properly_ good to go now.

**Comment by tianon** [comment]
With this it's probably ~safe to revert #9 / #8, but it feels better to take small steps (and that code is definitely working correctly ATM).

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
